export const ProductList = [
  { label: "चावल (Rice)", value: "चावल (Rice)" },
  { label: "चीनी (Cheeni)", value: "चीनी (Cheeni)" },
  { label: "आटा (Aata)", value: "आटा (Aata)" },
  { label: "जीरा (Jeera)", value: "जीरा (Jeera)" },
  { label: "गोलकी (Golakee)", value: "गोलकी (Golakee)" },
  { label: "मसूर दाल (Masoor Dal)", value: "मसूर दाल (Masoor Dal)" },
  { label: "मूंग दाल (Moong Dal)", value: "मूंग दाल (Moong Dal)" },
  { label: "चायपत्ती (Chaipatti)", value: "चायपत्ती (Chaipatti)" },
  { label: "रिफाइंड तेल (Refined Tel)", value: "रिफाइंड तेल (Refined Tel)" },
  { label: "सरसो तेल (Sarso Tel)", value: "सरसो तेल (Sarso Tel)" },
  { label: "व्हील सर्फ (Wheel Surf)", value: "व्हील सर्फ (Wheel Surf)" },
  { label: "मोगरा धूप (Mogra Dhoop)", value: "मोगरा धूप (Mogra Dhoop)" },
  { label: "मुकुल दाना (Mukul Daana)", value: "मुकुल दाना (Mukul Daana)" },
  { label: "किशमिश (Kishmish)", value: "किशमिश (Kishmish)" },
  { label: "लक्स साबुन ( LUX )", value: "लक्स साबुन ( LUX )" },
  {
    label: "पेप्सोडेंट (Pepsodent) - 2 pack",
    value: "पेप्सोडेंट (Pepsodent) - 2 pack",
  },
  { label: "नमक (Namak)", value: "नमक (Namak)" },
  { label: "बादाम (Badam)", value: "बादाम (Badam)" },
  {
    label: "धनिया पाउडर (Dhaniya Powder)",
    value: "धनिया पाउडर (Dhaniya Powder)",
  },
  { label: "मिर्च पाउडर (Mirch Powder)", value: "मिर्च पाउडर (Mirch Powder)" },
  {
    label: "कश्मीरी लाल मिर्ची (Kashmiri Lal Mirch)",
    value: "कश्मीरी लाल मिर्ची (Kashmiri Lal Mirch)",
  },
  { label: "टोमेटो सॉस (Tomato Sauce)", value: "टोमेटो सॉस (Tomato Sauce)" },
  {
    label: "गार्नियर केश कला (Garnier Kesh Kala)",
    value: "गार्नियर केश कला (Garnier Kesh Kala)",
  },
  { label: "सूजी (Suji)", value: "सूजी (Suji)" },
  { label: "तेज पत्ता (Tej Patta)", value: "तेज पत्ता (Tej Patta)" },
  { label: "इंडिया गेट (India Gate)", value: "इंडिया गेट (India Gate)" },
  { label: "माचिस (Matchis)", value: "माचिस (Matchis)" },
  { label: "लाइज़ोल (Lizol)", value: "लाइज़ोल (Lizol)" },
  { label: "हार्पिक (Harpic)", value: "हार्पिक (Harpic)" },
  {
    label: "मेरीगोल्ड  बिस्किट्स (Marigold Biscuits)",
    value: "मेरीगोल्ड  बिस्किट्स (Marigold Biscuits)",
  },
  {
    label: "मोनैको  बिस्किट्स (Monaico Biscuits)",
    value: "मोनैको  बिस्किट्स (Monaico Biscuits)",
  },
  { label: "दालमोट (Mixture)", value: "दालमोट (Mixture)" },
  { label: "सत्तू (Sattu)", value: "सत्तू (Sattu)" },
  { label: "चना (Chana)", value: "चना (Chana)" },
  { label: "मिठ्ठा (Mittha)", value: "मिठ्ठा (Mittha)" },
  { label: "चना दाल (Chana Dal)", value: "चना दाल (Chana Dal)" },
  { label: "सोयाबीन (Soyabean)", value: "सोयाबीन (Soyabean)" },
  {
    label: "बिरयानी मसाला (Briyani Masala)",
    value: "बिरयानी मसाला (Briyani Masala)",
  },
  { label: "बजाज तेल (Bajaj Tel)", value: "बजाज तेल (Bajaj Tel)" },
  { label: "घी (Ghee)", value: "घी (Ghee)" },
  { label: "चन्दन (Chandan)", value: "चन्दन (Chandan)" },
  {
    label: "जॉनसन बेबी क्रीम (Johnson Baby Cream)",
    value: "जॉनसन बेबी क्रीम (Johnson Baby Cream)",
  },
  {
    label: "पोंड्स फेस वाश (Ponds Face Wash)",
    value: "पोंड्स फेस वाश (Ponds Face Wash)",
  },
  {
    label: "जॉनसन बेबी पाउडर (Johnson Baby Powder)",
    value: "जॉनसन बेबी पाउडर (Johnson Baby Powder)",
  },
  { label: "डेटोल (Dettol)", value: "डेटोल (Dettol)" },
  { label: "डव शैम्पू (Dove Shampoo)", value: "डव शैम्पू (Dove Shampoo)" },
  { label: "सेवई (Sewai)", value: "सेवई (Sewai)" },
  { label: "मैदा (Maida)", value: "मैदा (Maida)" },
  {
    label: "शिमला मिर्च पाउडर (Shimla Mirch Powder)",
    value: "शिमला मिर्च पाउडर (Shimla Mirch Powder)",
  },
  { label: "भिंडी चिप्स (Bhindi Chips)", value: "भिंडी चिप्स (Bhindi Chips)" },
];

export const WeightInKilogram = [
  { label: "1 kg", value: "1 kg" },
  { label: "1.5 kg", value: "1.5 kg" },
  { label: "2 kg", value: "2 kg" },
  { label: "2.5 kg", value: "2.5 kg" },
  { label: "3 kg", value: "3 kg" },
  { label: "3.5 kg", value: "3.5 kg" },
  { label: "4 kg", value: "4 kg" },
  { label: "4.5 kg", value: "4.5 kg" },
  { label: "5 kg", value: "5 kg" },
  { label: "5.5 kg", value: "5.5 kg" },
  { label: "6 kg", value: "6 kg" },
  { label: "6.5 kg", value: "6.5 kg" },
  { label: "7 kg", value: "7 kg" },
  { label: "7.5 kg", value: "7.5 kg" },
  { label: "8 kg", value: "8 kg" },
  { label: "8.5 kg", value: "8.5 kg" },
  { label: "9 kg", value: "9 kg" },
  { label: "9.5 kg", value: "9.5 kg" },
  { label: "10 kg", value: "10 kg" },
  { label: "11 kg", value: "11 kg" },
  { label: "12 kg", value: "12 kg" },
  { label: "15 kg", value: "15 kg" },
  { label: "20 kg", value: "20 kg" },
  { label: "25 kg", value: "25 kg" },
  { label: "30 kg", value: "30 kg" },
];

export const WeightInGram = [
  { label: "20 gram", value: "20 gram" },
  { label: "25 gram", value: "25 gram" },
  { label: "30 gram", value: "30 gram" },
  { label: "50 gram", value: "50 gram" },
  { label: "100 gram", value: "100 gram" },
  { label: "150 gram", value: "150 gram" },
  { label: "200 gram", value: "200 gram" },
  { label: "250 gram", value: "250 gram" },
  { label: "300 gram", value: "300 gram" },
  { label: "400 gram", value: "400 gram" },
  { label: "500 gram", value: "500 gram" },
  { label: "750 gram", value: "750 gram" },
];
